Improved scripts, made their interface consistent.

diff --git a/ftdmp-build-complex b/ftdmp-build-complex
--- a/ftdmp-build-complex
+++ b/ftdmp-build-complex
@@ -4,7 +4,7 @@ function print_help_and_exit
 {
 cat >&2 << 'EOF'
 
-'ftdmp-build' generates structure files from docking results produced by 'ftdmp-dock'
+'ftdmp-build-complex' generates structure files from docking results
 
 Options:
     --monomer1                string  *  monomer 1 input file path
@@ -17,11 +17,11 @@ Standard input:
     space-separated table of docking results
 
 Standard output:
-    list of generated files
+    space-separated table of docking results
     
 Example:
 
-    cat docking_results_table.txt | head -5 | ftdmp-build -m1 monomer1.pdb -m2 monomer2.pdb -o complexes/
+    cat docking_results_table.txt | head -5 | ftdmp-build-complex --monomer1 monomer1.pdb --monomer2 monomer2.pdb --output-prefix complexes/
 
 EOF
 exit 1
@@ -37,7 +37,7 @@ fi
 if [[ $ZEROARG == *"/"* ]]
 then
 	cd $(dirname $ZEROARG)
-	export PATH=$(pwd):$PATH
+	export PATH="$(pwd):${PATH}"
 	cd - &> /dev/null
 fi
 
@@ -139,5 +139,14 @@ cd - &> /dev/null
 mkdir -p "$(dirname "${OUTPUT_PREFIX}name${OUTPUT_SUFFIX}")"
 
 find "${TMPLDIR}/docklines" -type f -not -empty \
-| xargs -L 1 -P 1 voronota-js --no-setup-defaults
+| xargs -L 1 -P 1 voronota-js --no-setup-defaults \
+> "${TMPLDIR}/output_file_paths"
+
+if [ ! -s "${TMPLDIR}/output_file_paths" ]
+then
+	echo >&2 "Error: no files generated"
+	exit 1
+fi
+
+cat "${TMPLDIR}/input"
 
diff --git a/ftdmp-calc-interface-cadscore-matrix b/ftdmp-calc-interface-cadscore-matrix
--- a/ftdmp-calc-interface-cadscore-matrix
+++ b/ftdmp-calc-interface-cadscore-matrix
@@ -7,11 +7,12 @@ cat >&2 << 'EOF'
 'ftdmp-calc-interface-cadscore-matrix' computes similarity matrix for docking results produced by 'ftdmp-dock'
 
 Options:
+    --matrix-output           string  *  matrix output file path
     --input-prefix            string     input file path prefix
-    --input-suffix            string     input file path suffix
-    --monomer1                string  *  static monomer input file path
-    --monomer2                string  *  mobile monomer input file path
-    --parallel-parts          number     total number of parallel parts, default is 1
+    --input-suffix            string     input file path suffix, default is '.pdb'
+    --monomer1                string     static monomer input file path
+    --monomer2                string     mobile monomer input file path
+    --parallel                number     total number of parallel parts, default is 1
     --parameters              string     parameters to pass to voronota-js-fast-iface-voromqa, default is ''
     --help | -h                          flag to display help message and exit
 
@@ -19,11 +20,11 @@ Standard input:
     space-separated table of docking results
 
 Standard output:
-    space-separated table of scoring results
+    space-separated table of docking results
     
 Example:
 
-    cat docking_results_table.txt | ftdmp-calc-interface-cadscore-matrix -m1 monomer1.pdb -m2 monomer2.pdb --parallel-parts 16
+    cat docking_results_table.txt | ftdmp-calc-interface-cadscore-matrix --monomer1 monomer1.pdb --monomer2 monomer2.pdb --parallel 16
 
 EOF
 exit 1
@@ -45,8 +46,9 @@ fi
 
 command -v voronota-js-fast-iface-cadscore &> /dev/null || { echo >&2 "Error: 'voronota-js-fast-iface-cadscore' executable not in binaries path"; exit 1; }
 
+MATRIX_OUTPUT=""
 INPUT_PREFIX=""
-INPUT_SUFFIX=""
+INPUT_SUFFIX=".pdb"
 MONOMERFILE1=""
 MONOMERFILE2=""
 PARALLEL_PARTS="1"
@@ -60,6 +62,10 @@ do
 	OPTARG="$2"
 	shift
 	case $OPTION in
+	--matrix-output)
+		MATRIX_OUTPUT="$OPTARG"
+		shift
+		;;
 	--input-prefix)
 		INPUT_PREFIX="$OPTARG"
 		shift
@@ -78,7 +84,7 @@ do
 		USE_MONOMERS="true"
 		shift
 		;;
-	--parallel-parts)
+	--parallel)
 		PARALLEL_PARTS="$OPTARG"
 		shift
 		;;
@@ -99,6 +105,12 @@ done
 if [ "$HELP_MODE" == "true" ]
 then
 	print_help_and_exit
+fi
+
+if [ -z "$MATRIX_OUTPUT" ]
+then
+	echo >&2 "Error: matrix output file path not provided"
+	exit 1
 fi
 
 if [ "$USE_MONOMERS" == "true" ]
@@ -176,5 +188,8 @@ then
 	exit 1
 fi
 
-cat "${TMPLDIR}/output"
+mkdir -p "$(dirname "$MATRIX_OUTPUT")"
+cat "${TMPLDIR}/output" > "$MATRIX_OUTPUT"
+
+cat "${TMPLDIR}/input"
 
diff --git a/ftdmp-calc-ranks-jury-scores b/ftdmp-calc-ranks-jury-scores
--- a/ftdmp-calc-ranks-jury-scores
+++ b/ftdmp-calc-ranks-jury-scores
@@ -8,17 +8,22 @@ cat >&2 << 'EOF'
 
 Options:
     --similarities            string  *  similarities table input file path
-    --ranks                   string  *  ranks table input file path
+    --rank-columns            string  *  rank column names to use
     --top-slices              string     top slices to use, default is '10 20 30 40 50'
     --cluster                 number     similarity threshold to select cluster representatives, default is 1.0
+    --colnames-prefix         string     prefix for output column names, default is 'RJS_'
+    --adjoin                             flag to output results joined with input
     --help | -h                          flag to display help message and exit
 
+Standard input:
+    space-separated table of docking results
+    
 Standard output:
-    space-separated table of sorted ranks jury scores
+    space-separated table of scoring results
     
 Example:
 
-    ftdmp-calc-ranks-jury-scores --similarities similarities.txt --ranks ranks.txt --top-slices '10 20 30 99999'
+    ftdmp-calc-ranks-jury-scores --similarities similarities.txt --rank-columns "colname1 colname2 colname3" --top-slices '10 20 30 99999'
 
 EOF
 exit 1
@@ -41,9 +46,11 @@ fi
 command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
 
 SIMILARITIESFILE=""
-RANKSFILE=""
+RANKCOLUMNS=""
 TOPSLICES="10 20 30 40 50"
 CLUSTERTHRESHOLD="1"
+COLNAMES_PREFIX="RJS_"
+ADJOIN="false"
 HELP_MODE="false"
 while [[ $# > 0 ]]
 do
@@ -55,8 +62,8 @@ do
 		SIMILARITIESFILE="$OPTARG"
 		shift
 		;;
-	--ranks)
-		RANKSFILE="$OPTARG"
+	--rank-columns)
+		RANKCOLUMNS="$OPTARG"
 		shift
 		;;
 	--top-slices)
@@ -66,6 +73,13 @@ do
 	--cluster)
 		CLUSTERTHRESHOLD="$OPTARG"
 		shift
+		;;
+	--colnames-prefix)
+		COLNAMES_PREFIX="$OPTARG"
+		shift
+		;;
+	--adjoin)
+		ADJOIN="true"
 		;;
 	-h|--help)
 		HELP_MODE="true"
@@ -88,21 +102,9 @@ then
 	exit 1
 fi
 
-if [ ! -s "$SIMILARITIESFILE" ]
+if [ -z "$RANKCOLUMNS" ]
 then
-	echo >&2 "Error: no similarities input file '$SIMILARITIESFILE'"
-	exit 1
-fi
-
-if [ -z "$RANKSFILE" ]
-then
-	echo >&2 "Error: no ranks input file specified"
-	exit 1
-fi
-
-if [ ! -s "$RANKSFILE" ]
-then
-	echo >&2 "Error: no ranks input file '$RANKSFILE'"
+	echo >&2 "Error: no rank columns specified"
 	exit 1
 fi
 
@@ -114,6 +116,33 @@ fi
 
 readonly TMPLDIR=$(mktemp -d)
 trap "rm -r $TMPLDIR" EXIT
+
+cat > "${TMPLDIR}/input"
+
+if [ ! -s "${TMPLDIR}/input" ]
+then
+	echo >&2 "Error: no input data in stdin"
+	exit 1
+fi
+
+if [ ! -s "$SIMILARITIESFILE" ]
+then
+	echo >&2 "Error: no similarities input file '$SIMILARITIESFILE'"
+	exit 1
+fi
+
+RANKSFILE="${TMPLDIR}/ranks"
+
+cat "${TMPLDIR}/input" \
+| ftdmp-extract-table-columns ID $RANKCOLUMNS \
+| tail -n +2 \
+> "$RANKSFILE"
+
+if [ ! -s "$RANKSFILE" ]
+then
+	echo >&2 "Error: failed to extract rank columns"
+	exit 1
+fi
 
 {
 cat << EOF
@@ -127,5 +156,31 @@ EOF
 } \
 | tr '\n' ' ' \
 | sed 's/$/\n/' \
-| voronota-js --no-setup-defaults
+| voronota-js --no-setup-defaults \
+> "${TMPLDIR}/jury_scores"
+
+if [ ! -s "${TMPLDIR}/jury_scores" ]
+then
+	echo >&2 "Error: failed to compute jury scores"
+	exit 1
+fi
+
+{
+echo "ID $(echo $TOPSLICES)" | sed "s/\s\+/ top/g" | awk '{print $0 " rank"}' | sed "s/\s\+/ ${COLNAMES_PREFIX}/g"
+cat "${TMPLDIR}/jury_scores" | awk '{print $0 " " NR}'
+} \
+> "${TMPLDIR}/output"
+
+if [ ! -s "${TMPLDIR}/output" ]
+then
+	echo >&2 "Error: no output produced"
+	exit 1
+fi
+
+if [ "$ADJOIN" == "true" ]
+then
+	ftdmp-join-tables "${TMPLDIR}/input" "${TMPLDIR}/output"
+else
+	cat "${TMPLDIR}/output"
+fi
 
diff --git a/ftdmp-prepare-monomer b/ftdmp-prepare-monomer
--- a/ftdmp-prepare-monomer
+++ b/ftdmp-prepare-monomer
@@ -7,12 +7,12 @@ cat >&2 << 'EOF'
 'ftdmp-prepare-monomer' prepares a monomer structure for docking with 'ftdmp-dock'
 
 Options:
-    --input | -i              string  *  input file path
-    --output | -o             string  *  output file path for full monomer
+    --input                   string  *  input file path
+    --output                  string  *  output file path for full monomer
     --restrict-input          string     query to restrict input atoms, default is '[]'
     --randomize                          flag to center and pseudo-randomly spin the structure
     --random-seed             number     seed for pseudo-random spinning, default is 1, 0 means current time
-    --prepare-for-relax                  flag to make structure ready for relaxation by adding missing heavy and hydrogen atoms
+    --forcefield              string     forcefield name to make structure ready for relaxation, default is ''
     --conda-path              string     conda installation path needed to prepare for relaxation, default is ''
     --conda-env               string     conda environment name needed to prepare for relaxation, default is ''
     --help | -h                          flag to display help message and exit
@@ -22,7 +22,7 @@ Examples:
 	ftdmp-prepare-monomer --input input/model.pdb --output output/prepared_model
 
     ftdmp-prepare-monomer --input input/model.pdb --output output/prepared_model --restrict-input '[-chain A]' \
-      --randomize --prepare-for-relax --conda-path ~/anaconda3 --conda-env alphafold2
+      --randomize --forcefield --conda-path ~/anaconda3 --conda-env alphafold2
 
 EOF
 exit 1
@@ -38,7 +38,7 @@ fi
 if [[ $ZEROARG == *"/"* ]]
 then
 	cd $(dirname $ZEROARG)
-	export PATH=$(pwd):$PATH
+	export PATH="$(pwd):${PATH}"
 	cd - &> /dev/null
 fi
 
@@ -49,10 +49,10 @@ OUTFILE=""
 OUTFILE_FOR_FTDOCK=""
 RESTRICT_INPUT="[]"
 RANDOM_SEED="1"
+FORCEFIELD=""
 CONDA_PATH=""
 CONDA_ENV=""
 RANDOMIZE="false"
-PREPARE_FOR_RELAX="false"
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -61,11 +61,11 @@ do
 	OPTARG="$2"
 	shift
 	case $OPTION in
-	-i|--input)
+	--input)
 		INFILE="$OPTARG"
 		shift
 		;;
-	-o|--output)
+	--output)
 		OUTFILE="$OPTARG"
 		shift
 		;;
@@ -81,6 +81,10 @@ do
 		RANDOM_SEED="$OPTARG"
 		shift
 		;;
+	--forcefield)
+		FORCEFIELD="$OPTARG"
+		shift
+		;;
 	--conda-path)
 		CONDA_PATH="$OPTARG"
 		shift
@@ -91,9 +95,6 @@ do
 		;;
 	--randomize)
 		RANDOMIZE="true"
-		;;
-	--prepare-for-relax)
-		PREPARE_FOR_RELAX="true"
 		;;
 	-h|--help)
 		HELP_MODE="true"
@@ -125,6 +126,12 @@ fi
 if [ ! -s "$INFILE" ]
 then
 	echo >&2 "Error: input file '$INFILE' does not exist"
+	exit 1
+fi
+
+if [ -n "$FORCEFIELD" ] && [ "$FORCEFIELD" != "amber99sb" ] && [ "$FORCEFIELD" != "amber14-all" ] && [ "$FORCEFIELD" != "charmm36" ]
+then
+	echo >&2 "Error: invalid forcefield name '$FORCEFIELD'"
 	exit 1
 fi
 
@@ -176,42 +183,13 @@ else
 	cat "$INFILE" > "$TMPLDIR/structure_stage1.pdb"
 fi
 
-if [ "$PREPARE_FOR_RELAX" == "true" ]
+if [ -n "$FORCEFIELD" ]
 then
-	command -v ftdmp-relax-with-openmm &> /dev/null || { echo >&2 "Error: 'ftdmp-relax-with-openmm' executable not in binaries path"; exit 1; }
-	
-	if [ -z "$CONDA_DEFAULT_ENV" ]
-	then
-		if [ -z "$CONDA_PATH" ]
-		then
-			echo >&2 "Error: not in conda environment, and the conda path is not provided"
-			exit 1
-		fi
-		if [ ! -s "${CONDA_PATH}/bin/activate" ]
-		then
-			echo >&2 "Error: no conda activation script '${CONDA_PATH}/bin/activate'"
-			exit 1
-		fi
-		source "${CONDA_PATH}/bin/activate"
-	fi
-	
-	if [ -n "$CONDA_ENV" ]
-	then
-		if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]
-		then
-			conda activate "$CONDA_ENV"
-		fi
-		
-		if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]
-		then
-			echo >&2 "Error: no '$CONDA_ENV' environment"
-			exit 1
-		fi
-	fi
-	
 	ftdmp-relax-with-openmm \
+	  --conda-path "$CONDA_PATH" \
+	  --conda-env "$CONDA_ENV" \
 	  --no-simulation \
-	  --forcefield amber14-all \
+	  --forcefield "$FORCEFIELD" \
 	  --trim-output \
 	  --input "$TMPLDIR/structure_stage1.pdb" \
 	  --output "$TMPLDIR/structure_stage2.pdb"
