Modified ftdock to work with smaller angle steps.

diff --git a/ftdmp-dock-two-monomers-with-ftdock b/ftdmp-dock-two-monomers-with-ftdock
--- a/ftdmp-dock-two-monomers-with-ftdock
+++ b/ftdmp-dock-two-monomers-with-ftdock
@@ -171,9 +171,9 @@ then
 	exit 1
 fi
 
-if [ -z "$FTDOCK_ANGLE_STEP" ] || [ "$FTDOCK_ANGLE_STEP" -ne "$FTDOCK_ANGLE_STEP" ] || [ "$FTDOCK_ANGLE_STEP" -lt "9" ]
+if [ -z "$FTDOCK_ANGLE_STEP" ] || [ "$FTDOCK_ANGLE_STEP" -ne "$FTDOCK_ANGLE_STEP" ] || [ "$FTDOCK_ANGLE_STEP" -lt "3" ]
 then
-	echo >&2 "Error: invalid ftdock angle step parameter '$FTDOCK_ANGLE_STEP', must be an integer >=9 and a factor of 180"
+	echo >&2 "Error: invalid ftdock angle step parameter '$FTDOCK_ANGLE_STEP', must be an integer >=3 and a factor of 180"
 	exit 1
 fi
 
