Emproved testing workflow.

diff --git a/ftdmp-build-complex b/ftdmp-build-complex
--- a/ftdmp-build-complex
+++ b/ftdmp-build-complex
@@ -10,7 +10,6 @@ Options:
     --monomer1 | -m1          string  *  monomer 1 input file path
     --monomer2 | -m2          string  *  monomer 2 input file path
     --output-prefix | -o      string  *  output file path prefix, default is ''
-    --voronota-js-path        string     voronota-js executables path, default is ''
     --help | -h                          flag to display help message and exit
 
 Standard input:
@@ -41,10 +40,11 @@ then
 	cd - &> /dev/null
 fi
 
+command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js-fast-iface-voromqa' executable not in binaries path"; exit 1; }
+
 MONOMERFILE1=""
 MONOMERFILE2=""
 OUTPUT_PREFIX=""
-VORONOTA_JS_PATH=""
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -63,10 +63,6 @@ do
 		;;
 	-o|--output-prefix)
 		OUTPUT_PREFIX="$OPTARG"
-		shift
-		;;
-	--voronota-js-path)
-		VORONOTA_JS_PATH="$OPTARG"
 		shift
 		;;
 	-h|--help)
@@ -107,13 +103,6 @@ then
 	echo >&2 "Error: no mobile input file '$MONOMERFILE2'"
 	exit 1
 fi
-
-if [ -n "$VORONOTA_JS_PATH" ]
-then
-	export PATH=${VORONOTA_JS_PATH}:${PATH}
-fi
-
-command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js-fast-iface-voromqa' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 trap "rm -r $TMPLDIR" EXIT
diff --git a/ftdmp-dock b/ftdmp-dock
--- a/ftdmp-dock
+++ b/ftdmp-dock
@@ -12,7 +12,6 @@ Options:
     --logs-output             string     logs output directory path
     --parallel-parts          number     total number of parallel parts, default is 1
     --parallel-id             number     ID of the parallel part to process, default is '' for processing all parts
-    --voronota-js-path        string     voronota-js executables path, default is ''
     --help | -h                          flag to display help message and exit
 
 Standard output:
@@ -46,6 +45,7 @@ then
 	cd - &> /dev/null
 fi
 
+command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
 command -v ftdmp-prepare-monomer &> /dev/null || { echo >&2 "Error: 'ftdmp-prepare-monomer' executable not in binaries path"; exit 1; }
 command -v ftdock &> /dev/null || { echo >&2 "Error: 'ftdock' executable not in binaries path"; exit 1; }
 
@@ -54,7 +54,6 @@ MONOMERFILE2=""
 OUTDIR=""
 PARALLEL_PARTS="1"
 PARALLEL_ID=""
-VORONOTA_JS_PATH=""
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -81,10 +80,6 @@ do
 		;;
 	--parallel-id)
 		PARALLEL_ID="$OPTARG"
-		shift
-		;;
-	--voronota-js-path)
-		VORONOTA_JS_PATH="$OPTARG"
 		shift
 		;;
 	-h|--help)
@@ -140,13 +135,6 @@ then
 		exit 1
 	fi
 fi
-
-if [ -n "$VORONOTA_JS_PATH" ]
-then
-	export PATH=${VORONOTA_JS_PATH}:${PATH}
-fi
-
-command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
 
 if [ -z "$OUTDIR" ]
 then
diff --git a/ftdmp-prepare-monomer b/ftdmp-prepare-monomer
--- a/ftdmp-prepare-monomer
+++ b/ftdmp-prepare-monomer
@@ -12,7 +12,6 @@ Options:
     --restrict-input          string     query to restrict input atoms, default is '[]'
     --randomize                          flag to center and pseudo-randomly spin the structure
     --random-seed             number     seed for pseudo-random spinning, default is 1, 0 means current time
-    --voronota-js-path        string     voronota-js executables path, default is ''
     --prepare-for-relax                  flag to make structure ready for relaxation by adding missing heavy and hydrogen atoms
     --conda-path              string     conda installation path needed to prepare for relaxation, default is ''
     --conda-env               string     conda environment name needed to prepare for relaxation, default is ''
@@ -20,12 +19,10 @@ Options:
 
 Examples:
 
-	ftdmp-prepare-monomer --input input/model.pdb --output output/prepared_model \
-	  --voronota-js-path ~/git/voronota/expansion_js
+	ftdmp-prepare-monomer --input input/model.pdb --output output/prepared_model
 
     ftdmp-prepare-monomer --input input/model.pdb --output output/prepared_model --restrict-input '[-chain A]' \
-      --randomize --voronota-js-path ~/git/voronota/expansion_js \
-      --prepare-for-relax --conda-path ~/anaconda3 --conda-env alphafold2
+      --randomize --prepare-for-relax --conda-path ~/anaconda3 --conda-env alphafold2
 
 EOF
 exit 1
@@ -45,12 +42,13 @@ then
 	cd - &> /dev/null
 fi
 
+command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
+
 INFILE=""
 OUTFILE=""
 OUTFILE_FOR_FTDOCK=""
 RESTRICT_INPUT="[]"
 RANDOM_SEED="1"
-VORONOTA_JS_PATH=""
 CONDA_PATH=""
 CONDA_ENV=""
 RANDOMIZE="false"
@@ -81,10 +79,6 @@ do
 		;;
 	--random-seed)
 		RANDOM_SEED="$OPTARG"
-		shift
-		;;
-	--voronota-js-path)
-		VORONOTA_JS_PATH="$OPTARG"
 		shift
 		;;
 	--conda-path)
@@ -133,13 +127,6 @@ then
 	echo >&2 "Error: input file '$INFILE' does not exist"
 	exit 1
 fi
-
-if [ -n "$VORONOTA_JS_PATH" ]
-then
-	export PATH=${VORONOTA_JS_PATH}:${PATH}
-fi
-
-command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 trap "rm -r $TMPLDIR" EXIT
diff --git a/ftdmp-score b/ftdmp-score
--- a/ftdmp-score
+++ b/ftdmp-score
@@ -10,7 +10,6 @@ Options:
     --monomer1 | -m1          string  *  monomer 1 input file path
     --monomer2 | -m2          string  *  monomer 2 input file path
     --parallel-parts          number     total number of parallel parts, default is 1
-    --voronota-js-path        string     voronota-js executables path, default is ''
     --parameters              string     parameters to pass to voronota-js-fast-iface-voromqa, default is ''
     --colnames-prefix         string     prefix for output column names
     --join-tables                        flag to output joined input and result tables
@@ -44,10 +43,11 @@ then
 	cd - &> /dev/null
 fi
 
+command -v voronota-js-fast-iface-voromqa &> /dev/null || { echo >&2 "Error: 'voronota-js-fast-iface-voromqa' executable not in binaries path"; exit 1; }
+
 MONOMERFILE1=""
 MONOMERFILE2=""
 PARALLEL_PARTS="1"
-VORONOTA_JS_PATH=""
 IFACE_VOROMQA_PARAMETERS=""
 COLNAMES_PREFIX=""
 JOINED_TABLES="false"
@@ -69,10 +69,6 @@ do
 		;;
 	--parallel-parts)
 		PARALLEL_PARTS="$OPTARG"
-		shift
-		;;
-	--voronota-js-path)
-		VORONOTA_JS_PATH="$OPTARG"
 		shift
 		;;
 	--parameters)
@@ -130,13 +126,6 @@ then
 	echo >&2 "Error: invalid number of parallel parts '$PARALLEL_PARTS', must be a positive number"
 	exit 1
 fi
-
-if [ -n "$VORONOTA_JS_PATH" ]
-then
-	export PATH=${VORONOTA_JS_PATH}:${PATH}
-fi
-
-command -v voronota-js-fast-iface-voromqa &> /dev/null || { echo >&2 "Error: 'voronota-js-fast-iface-voromqa' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 trap "rm -r $TMPLDIR" EXIT
