Added caching option in relaxation script.

diff --git a/ftdmp-relax-with-openmm b/ftdmp-relax-with-openmm
--- a/ftdmp-relax-with-openmm
+++ b/ftdmp-relax-with-openmm
@@ -15,13 +15,14 @@ Options:
     --focus-second-sel        string     second selection of atoms to define interface not by chains, default is ''
     --conda-path              string     conda installation path, default is ''
     --conda-env               string     conda environment name, default is ''
-    --forcefield              string     forcefield combo name default is 'amber99sb', others are: 'amber14-all', 'amber14-all-no-water', 'charmm36'
+    --forcefield              string     forcefield combo name, default is 'amber99sb', others are: 'amber14-all', 'amber14-all-no-water', 'charmm36'
     --main-forcefield         string     main forcefield name, default is defined by the combo name, some others are: 'amber99sb', 'amber14-all', 'charmm36'
     --water-forcefield        string     water forcefiled name, default is defined by the combo name, some others are: '', 'amber99_obc', 'amber14/tip3pfb', 'charmm36/water'
     --max-iterations          number     max number of iterations, default is 100
     --score-at-end            string     mode for scoring interface at the end, default is '', others are: 'fast_iface', 'full_iface', 'full'
     --scoring-params          string     additional parameters for scoring, default is ''
     --multiple-tries          number     number of tries to generate and score interfaces, default is ''
+    --cache-dir               string     cache directory path to store results of past calls
     --force-cuda                         flag to force the platform to be CUDA
     --trim-output                        flag to restrict output to atoms of proteins and nucleic acids
     --no-preparation                     flag to not run any preparation of input structure before simulations
@@ -43,6 +44,9 @@ Examples:
 EOF
 exit 1
 }
+
+readonly ZEROARG=$0
+ALLARGS=("$@")
 
 if [ -z "$1" ]
 then
@@ -70,11 +74,14 @@ MAX_ITERATIONS="100"
 SCORE_AT_END=""
 SCORING_PARAMS=""
 MULTIPLE_TRIES=""
+CACHE_DIR=""
 FORCE_CUDA="false"
 TRIM_OUTPUT="false"
 NO_PREPARATION="false"
 LIMIT_PREPARATION="false"
 NO_SIMULATION="false"
+JUST_OUTPUT_FROM_DIR=""
+ARCHIVE_WHEN_JUST_OUTPUT_FROM_DIR=""
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -143,6 +150,10 @@ do
 		MULTIPLE_TRIES="$OPTARG"
 		shift
 		;;
+	--cache-dir)
+		CACHE_DIR="$OPTARG"
+		shift
+		;;
 	--force-cuda)
 		FORCE_CUDA="true"
 		;;
@@ -151,8 +162,10 @@ do
 		;;
 	--no-preparation)
 		NO_PREPARATION="true"
+		LIMIT_PREPARATION="false"
 		;;
 	--limit-preparation)
+		NO_PREPARATION="false"
 		LIMIT_PREPARATION="true"
 		;;
 	--full-preparation)
@@ -161,6 +174,14 @@ do
 		;;
 	--no-simulation)
 		NO_SIMULATION="true"
+		;;
+	--jofd)
+		JUST_OUTPUT_FROM_DIR="$OPTARG"
+		shift
+		;;
+	--awjofd)
+		ARCHIVE_WHEN_JUST_OUTPUT_FROM_DIR="$OPTARG"
+		shift
 		;;
 	-h|--help)
 		HELP_MODE="true"
@@ -175,6 +196,68 @@ done
 if [ "$HELP_MODE" == "true" ]
 then
 	print_help_and_exit
+fi
+
+if [ -z "$INFILE" ]
+then
+	echo >&2 "Error: input file path not provided"
+	exit 1
+fi
+
+if [ -z "$OUTFILE" ]
+then
+	echo >&2 "Error: output file path not provided"
+	exit 1
+fi
+
+if [ ! -s "$INFILE" ]
+then
+	echo >&2 "Error: input file '$INFILE' does not exist"
+	exit 1
+fi
+
+if [ -n "$JUST_OUTPUT_FROM_DIR" ]
+then
+	if [ -s "$JUST_OUTPUT_FROM_DIR/scoring_results.txt" ]
+	then
+		cat "$JUST_OUTPUT_FROM_DIR/scoring_results.txt"
+	fi
+	
+	if [ -s "$JUST_OUTPUT_FROM_DIR/openmm_errors.txt" ]
+	then
+		cat "$JUST_OUTPUT_FROM_DIR/openmm_errors.txt" >&2
+	fi
+	
+	if [ -s "$JUST_OUTPUT_FROM_DIR/relaxed.pdb" ]
+	then
+		if [ -n "$OUTFILE" ] && [ "$OUTFILE" != "/dev/null" ]
+		then
+			if [ "$OUTFILE" == "_same_as_input" ]
+			then
+				cat "$JUST_OUTPUT_FROM_DIR/relaxed.pdb" > "$INFILE"
+			else
+				mkdir -p "$(dirname "$OUTFILE")"
+				cat "$JUST_OUTPUT_FROM_DIR/relaxed.pdb" > "$OUTFILE"
+			fi
+		fi
+	else
+		echo >&2 "Error: no relaxed structure produced"
+	fi
+	
+	if [ -n "$ARCHIVE_WHEN_JUST_OUTPUT_FROM_DIR" ] && [ ! -s "$ARCHIVE_WHEN_JUST_OUTPUT_FROM_DIR" ]
+	then
+		mkdir -p "$(dirname "$ARCHIVE_WHEN_JUST_OUTPUT_FROM_DIR")"
+		tar -czf "$ARCHIVE_WHEN_JUST_OUTPUT_FROM_DIR" \
+		  -C "$JUST_OUTPUT_FROM_DIR" \
+		  $(find "$JUST_OUTPUT_FROM_DIR" -type f | xargs -L 1 basename | egrep '^openmm_errors.txt$|^relaxed.pdb$|^scoring_results.txt$')
+	fi
+	
+	if [ -s "$JUST_OUTPUT_FROM_DIR/openmm_errors.txt" ] || [ ! -s "$JUST_OUTPUT_FROM_DIR/relaxed.pdb" ]
+	then
+		exit 1
+	fi
+	
+	exit 0
 fi
 
 if [ "$MAIN_FORCEFIELD" == "default" ] || [ "$WATER_FORCEFIELD" == "default" ]
@@ -230,24 +313,6 @@ then
 			WATER_FORCEFIELD="charmm36/water"
 		fi
 	fi
-fi
-
-if [ -z "$INFILE" ]
-then
-	echo >&2 "Error: input file path not provided"
-	exit 1
-fi
-
-if [ -z "$OUTFILE" ]
-then
-	echo >&2 "Error: output file path not provided"
-	exit 1
-fi
-
-if [ ! -s "$INFILE" ]
-then
-	echo >&2 "Error: input file '$INFILE' does not exist"
-	exit 1
 fi
 
 if [ "$FOCUS_MODE" != "interface_side_chains" ] && [ "$FOCUS_MODE" != "whole_interface" ] && [ "$FOCUS_MODE" != "not_interface" ] && [ "$FOCUS_MODE" != "whole_structure" ]
@@ -321,9 +386,54 @@ fi
 readonly TMPLDIR=$(mktemp -d)
 trap "rm -r $TMPLDIR" EXIT
 
-cp "$INFILE" "$TMPLDIR/input.pdb"
+CACHE_ARCHIVE=""
+
+if [ -n "$CACHE_DIR" ]
+then
+	{
+		cat "$INFILE"
+		echo "$FOCUS_MODE"
+		echo "$FOCUS_BASE"
+		echo "$FOCUS_FIRST_SEL"
+		echo "$FOCUS_SECOND_SEL"
+		echo "$MAIN_FORCEFIELD"
+		echo "$WATER_FORCEFIELD"
+		echo "$MAX_ITERATIONS"
+		echo "$SCORE_AT_END"
+		echo "$SCORING_PARAMS"
+		echo "$MULTIPLE_TRIES"
+		echo "$TRIM_OUTPUT"
+		echo "$NO_PREPARATION"
+		echo "$LIMIT_PREPARATION"
+		echo "$NO_SIMULATION"
+	} \
+	| md5sum | awk '{print $1}' \
+	> "${TMPLDIR}/hashsum.txt"
+	
+	HASHSUM="ftdmp-relax-with-openmm-$(cat ${TMPLDIR}/hashsum.txt)"
+	CACHE_ARCHIVE="${CACHE_DIR}/${HASHSUM}.tar.gz"
+	
+	if [ -s "$CACHE_ARCHIVE" ]
+	then
+		mkdir -p "${TMPLDIR}/saved_results"
+		
+		cp "$CACHE_ARCHIVE" "${TMPLDIR}/saved_results/archive.tar.gz"
+		
+		cd "${TMPLDIR}/saved_results"
+		tar -xf "./archive.tar.gz"
+		cd - &> /dev/null
+		
+		"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR/saved_results"
+		
+		exit 0
+	fi
+fi
+
+cat "$INFILE" > "$TMPLDIR/input.pdb"
 
 cd "$TMPLDIR"
+
+true > openmm_errors.txt
 
 if [ "$NO_PREPARATION" == "true" ]
 then
@@ -393,12 +503,14 @@ EOF
 	| sed "s|WATER_FORCEFIELD|${WATER_FORCEFIELD}|" \
 	> prepare.py
 	
-	python prepare.py
+	python prepare.py &>> openmm_errors.txt
 fi
 
 if [ ! -s "prepared.pdb" ]
 then
-	echo >&2 "Error: failed to prepare input"
+	echo "Error: failed to prepare input with OpenMM" &>> openmm_errors.txt
+	cd - &> /dev/null
+	"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR" --awjofd "$CACHE_ARCHIVE"
 	exit 1
 fi
 
@@ -514,7 +626,7 @@ EOF
 		seq 1 "$MULTIPLE_TRIES" \
 		| while read -r TRYNUM
 		do
-			python relax.py
+			python relax.py &>> openmm_errors.txt
 			if [ ! -s "relaxed.pdb" ]
 			then
 				exit 1
@@ -524,13 +636,15 @@ EOF
 		done
 		mv "original_prepared.pdb" "prepared.pdb"
 	else
-		python relax.py
+		python relax.py &>> openmm_errors.txt
 	fi
 fi
 
 if [ ! -s "relaxed.pdb" ] && [ ! -s "relaxed1.pdb" ]
 then
-	echo >&2 "Error: failed to relax with OpenMM"
+	echo "Error: failed to relax with OpenMM" &>> openmm_errors.txt
+	cd - &> /dev/null
+	"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR" --awjofd "$CACHE_ARCHIVE"
 	exit 1
 fi
 
@@ -543,26 +657,28 @@ else
 fi
 } > list_to_score.txt
 
-if [ "$SCORE_AT_END" == "fast_iface" ]
-then
-	if [ -n "$MULTIPLE_TRIES" ]
+{
+	if [ "$SCORE_AT_END" == "fast_iface" ]
 	then
-		cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list $SCORING_PARAMS | tee scores.txt | column -t
-		cp "$(cat scores.txt | awk '{print $1}' | egrep '^relaxed' | head -1)" "relaxed.pdb"
-	else
-		cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list $SCORING_PARAMS | column -t
+		if [ -n "$MULTIPLE_TRIES" ]
+		then
+			cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list $SCORING_PARAMS | tee scores.txt | column -t
+			cp "$(cat scores.txt | awk '{print $1}' | egrep '^relaxed' | head -1)" "relaxed.pdb"
+		else
+			cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list $SCORING_PARAMS | column -t
+		fi
 	fi
-fi
-
-if [ "$SCORE_AT_END" == "full_iface" ]
-then
-	cat list_to_score.txt | voronota-js-voromqa -i _list --inter-chain --processors 2 $SCORING_PARAMS | column -t
-fi
-
-if [ "$SCORE_AT_END" == "full" ]
-then
-	cat list_to_score.txt | voronota-js-voromqa -i _list --processors 2 $SCORING_PARAMS | column -t
-fi
+	
+	if [ "$SCORE_AT_END" == "full_iface" ]
+	then
+		cat list_to_score.txt | voronota-js-voromqa -i _list --inter-chain --processors 2 $SCORING_PARAMS | column -t
+	fi
+	
+	if [ "$SCORE_AT_END" == "full" ]
+	then
+		cat list_to_score.txt | voronota-js-voromqa -i _list --processors 2 $SCORING_PARAMS | column -t
+	fi
+} > scoring_results.txt
 
 if [ "$TRIM_OUTPUT" == "true" ]
 then
@@ -579,7 +695,7 @@ EOF
 	
 	if [ ! -s "trimmed_relaxed.pdb" ]
 	then
-		echo >&2 "Error: failed trim output"
+		echo >&2 "Error: failed to trim output"
 		exit 1
 	fi
 
@@ -588,16 +704,7 @@ fi
 
 cd - &> /dev/null
 
-if [ -n "$OUTFILE" ] && [ "$OUTFILE" != "/dev/null" ]
-then
-	if [ "$OUTFILE" == "_same_as_input" ]
-	then
-		mv "$TMPLDIR/relaxed.pdb" "$INFILE"
-	else
-		mkdir -p "$(dirname "$OUTFILE")"
-		mv "$TMPLDIR/relaxed.pdb" "$OUTFILE"
-	fi
-fi
+"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR" --awjofd "$CACHE_ARCHIVE"
 
 exit 0
 
