Added more checks of docking parameters.

diff --git a/ftdmp-dock-two-monomers b/ftdmp-dock-two-monomers
--- a/ftdmp-dock-two-monomers
+++ b/ftdmp-dock-two-monomers
@@ -159,9 +159,21 @@ then
 	fi
 fi
 
+if [ -z "$FTDOCK_KEEP" ] || [ "$FTDOCK_KEEP" -ne "$FTDOCK_KEEP" ] || [ "$FTDOCK_KEEP" -lt "1" ]
+then
+	echo >&2 "Error: invalid ftdock keep parameter '$FTDOCK_KEEP', must be a positive integer"
+	exit 1
+fi
+
+if [ -z "$FTDOCK_ANGLE_STEP" ] || [ "$FTDOCK_ANGLE_STEP" -ne "$FTDOCK_ANGLE_STEP" ] || [ "$FTDOCK_ANGLE_STEP" -lt "9" ]
+then
+	echo >&2 "Error: invalid ftdock angle step parameter '$FTDOCK_ANGLE_STEP', must be an integer greater than 8"
+	exit 1
+fi
+
 if [ -z "$MIN_GRID_SEP" ] || [ "$MIN_GRID_SEP" -ne "$MIN_GRID_SEP" ] || [ "$MIN_GRID_SEP" -lt "0" ]
 then
-	echo >&2 "Error: invalid minimum grid separation '$MIN_GRID_SEP', must be a positive integer"
+	echo >&2 "Error: invalid minimum grid separation '$MIN_GRID_SEP', must be a non-negative integer"
 	exit 1
 fi
 
