Improved cadscore matrix calculation.

diff --git a/ftdmp-calc-interface-cadscore-matrix b/ftdmp-calc-interface-cadscore-matrix
--- a/ftdmp-calc-interface-cadscore-matrix
+++ b/ftdmp-calc-interface-cadscore-matrix
@@ -13,6 +13,7 @@ Options:
     --monomer1                string     static monomer input file path
     --monomer2                string     mobile monomer input file path
     --subselect-contacts      string     query to subselect inter-chain contacts, default is '[]'
+    --parallel                number     total number of parallel parts, default is 1
     --help | -h                          flag to display help message and exit
 
 Standard input:
@@ -23,7 +24,7 @@ Standard output:
     
 Example:
 
-    cat docking_results_table.txt | ftdmp-calc-interface-cadscore-matrix --monomer1 monomer1.pdb --monomer2 monomer2.pdb
+    cat docking_results_table.txt | ftdmp-calc-interface-cadscore-matrix --monomer1 monomer1.pdb --monomer2 monomer2.pdb --parallel 16
 
 EOF
 exit 1
@@ -51,6 +52,7 @@ INPUT_SUFFIX=".pdb"
 MONOMERFILE1=""
 MONOMERFILE2=""
 SUBSELECT_CONTACTS="[]"
+PARALLEL_PARTS="1"
 USE_MONOMERS="false"
 HELP_MODE="false"
 
@@ -84,6 +86,10 @@ do
 		;;
 	--subselect-contacts)
 		SUBSELECT_CONTACTS="$OPTARG"
+		shift
+		;;
+	--parallel)
+		PARALLEL_PARTS="$OPTARG"
 		shift
 		;;
 	-h|--help)
@@ -134,6 +140,12 @@ then
 	fi
 fi
 
+if [ -z "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -ne "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -lt "1" ]
+then
+	echo >&2 "Error: invalid number of parallel parts '$PARALLEL_PARTS', must be a positive number"
+	exit 1
+fi
+
 readonly TMPLDIR=$(mktemp -d)
 trap "rm -r $TMPLDIR" EXIT
 
@@ -158,11 +170,11 @@ then
 	cd - &> /dev/null
 	
 	find "${TMPLDIR}/docklines" -type f -not -empty \
-	| voronota-js-fast-iface-cadscore-matrix --model-input-is-script --subselect-contacts "$SUBSELECT_CONTACTS"
+	| voronota-js-fast-iface-cadscore-matrix --model-input-is-script --subselect-contacts "$SUBSELECT_CONTACTS" --processors "$PARALLEL_PARTS"
 else
 	cat "${TMPLDIR}/input" \
 	| awk -v prefix="$INPUT_PREFIX" -v suffix="$INPUT_SUFFIX" '{if($1!="ID"){print prefix $1 suffix}}' \
-	| voronota-js-fast-iface-cadscore-matrix --subselect-contacts "$SUBSELECT_CONTACTS" \
+	| voronota-js-fast-iface-cadscore-matrix --subselect-contacts "$SUBSELECT_CONTACTS" --processors "$PARALLEL_PARTS" \
 	| sed "s/^\(\S\+\)${INPUT_SUFFIX}\s\+\(\S\+\)${INPUT_SUFFIX} /\1 \2 /"
 fi
 } \
