Made main workflow more universal, not only for hetero docking.

diff --git a/ftdmp-all b/ftdmp-all
--- a/ftdmp-all
+++ b/ftdmp-all
@@ -8,12 +8,14 @@ cat >&2 << 'EOF'
 
 Options:
     --job-name                string  *  job name
-    --static-file             string  *  static input file path
-    --static-sel              string     query to restrict static atoms, default is '[]'
-    --static-chain            string     chain name or chain renaming rule to apply for static atoms, default is ''
-    --mobile-file             string  *  mobile input file path
-    --mobile-sel              string     query to restrict mobile atoms, default is '[]'
-    --mobile-chain            string     chain name or chain renaming rule to apply for mobile atoms, default is ''
+    --pre-docked-input-dir    string     pre-docked input directory path 
+    --static-file             string     hetero docking static input file path
+    --static-sel              string     hetero docking query to restrict static atoms, default is '[]'
+    --static-chain            string     hetero docking chain name or chain renaming rule to apply for static atoms, default is ''
+    --mobile-file             string     hetero or homo docking mobile input file path
+    --mobile-sel              string     hetero or homo docking query to restrict mobile atoms, default is '[]'
+    --mobile-chain            string     hetero or homo docking chain name or chain renaming rule to apply for mobile atoms, default is ''
+    --symmetry-docking        string     homo docking symmetry to apply for the mobile input file, default is ''
     --subselect-contacts      string     query to subselect inter-chain contacts for scoring, default is '[]'
     --reference               string     input structure file to compute CAD-score with, default is ''
     --openmm-forcefield       string     forcefield name for OpenMM-based operations, default is ''
@@ -32,6 +34,8 @@ Options:
     --scoring-rank-names      string  *  rank names to use, or name of a standard set of rank names
     --scoring-ranks-top       number     number of top complexes to consider for each ranking, default is 100
     --scoring-jury-slices     string     slice sizes sequence definition for ranks jury scoring, default is '10 50'
+    --scoring-jury-cluster    number     clustering threshold for ranks jury scoring, default is 0.9
+    --scoring-jury-maxs       number     number of max values to use for ranks jury scoring, default is 5
     --redundancy-threshold    number     minimal ordered redundancy value to accept, default is 1
     --build-complexes         number     number of top complexes to build, default is 0
     --multiply-chains         string     options to multiply chains, default is ''
@@ -44,6 +48,9 @@ Options:
 Examples:
 
     ftdmp-all --job-name 'j1' --static-file './chainA.pdb' --mobile-file './chainB.pdb' \
+      --scoring-rank-names 'standard_for_protein_protein' --output-dir './results'
+
+    ftdmp-all --job-name 'j2' --pre-docked-input-dir './predocked' \
       --scoring-rank-names 'standard_for_protein_protein' --output-dir './results'
 
 EOF
@@ -64,12 +71,14 @@ then
 fi
 
 JOB_NAME=""
+PRE_DOCKED_INPUT_DIR=""
 STATIC_STRUCTURE_FILE=""
 STATIC_STRUCTURE_SELECTION="[]"
 STATIC_STRUCTURE_CHAIN=""
 MOBILE_STRUCTURE_FILE=""
 MOBILE_STRUCTURE_SELECTION="[]"
 MOBILE_STRUCTURE_CHAIN=""
+SYMMETRY_DOCKING=""
 INTERFACE_SUBSELECTION="[]"
 REFERENCE_STRUCTURE_FILE_FOR_COMPARISON=""
 OPENMM_FORCEFIELD=""
@@ -88,6 +97,8 @@ SCORING_TOP_STAGE1="1000"
 SCORING_RANKS=""
 SCORING_TOP_STAGE2="100"
 SCORING_RANKS_JURY_SLICES="10 50" 
+SCORING_RANKS_JURY_CLUSTER="0.9" 
+SCORING_RANKS_JURY_MAX_VALUES="5" 
 NUMBER_OF_COMPLEXES_TO_BUILD="0"
 REDUNDANCY_THRESHOLD="1"
 MULTIPLY_CHAINS=""
@@ -105,6 +116,10 @@ do
 	case $OPTION in
 	--job-name)
 		JOB_NAME="$OPTARG"
+		shift
+		;;
+	--pre-docked-input-dir)
+		PRE_DOCKED_INPUT_DIR="$OPTARG"
 		shift
 		;;
 	--static-file)
@@ -129,6 +144,10 @@ do
 		;;
 	--mobile-chain)
 		MOBILE_STRUCTURE_CHAIN="$OPTARG"
+		shift
+		;;
+	--symmetry-docking)
+		SYMMETRY_DOCKING="$OPTARG"
 		shift
 		;;
 	--subselect-contacts)
@@ -203,6 +222,14 @@ do
 		SCORING_RANKS_JURY_SLICES="$OPTARG"
 		shift
 		;;
+	--scoring-jury-cluster)
+		SCORING_RANKS_JURY_CLUSTER="$OPTARG"
+		shift
+		;;
+	--scoring-jury-maxs)
+		SCORING_RANKS_JURY_MAX_VALUES="$OPTARG"
+		shift
+		;;
 	--build-complexes)
 		NUMBER_OF_COMPLEXES_TO_BUILD="$OPTARG"
 		shift
@@ -248,15 +275,42 @@ fi
 
 [ -n "$JOB_NAME" ] || { echo >&2 "Error: job name not provided"; exit 1;}
 
-[ -n "$STATIC_STRUCTURE_FILE" ] || { echo >&2 "Error: static structure file not provided"; exit 1;}
-[ -s "$STATIC_STRUCTURE_FILE" ] || { echo >&2 "Error: static structure file non-existing or empty"; exit 1;}
+DOCKING_REGIME=""
 
-[ -n "$STATIC_STRUCTURE_SELECTION" ] || { echo >&2 "Error: static structure selection not defined"; exit 1; }
-
-[ -n "$MOBILE_STRUCTURE_FILE" ] || { echo >&2 "Error: mobile structure file not provided"; exit 1;}
-[ -s "$MOBILE_STRUCTURE_FILE" ] || { echo >&2 "Error: mobile structure file non-existing or empty"; exit 1;}
-
-[ -n "$MOBILE_STRUCTURE_SELECTION" ] || { echo >&2 "Error: mobile structure selection not defined"; exit 1; }
+if [ -n "$PRE_DOCKED_INPUT_DIR" ]
+then
+	[ -d "$PRE_DOCKED_INPUT_DIR" ] || { echo >&2 "Error: invalid pre-docked files input directory '$PRE_DOCKED_INPUT_DIR'"; exit 1;}
+	[ "$(find $PRE_DOCKED_INPUT_DIR -type f -not -empty | wc -l)" -gt "1" ] || { echo >&2 "Error: pre-docked files input directory '$PRE_DOCKED_INPUT_DIR' does not contain more than 1 file"; exit 1;}
+	
+	[ -z "$SYMMETRY_DOCKING" ] || { echo >&2 "Error: docking symmetry provided in pre-docked mode"; exit 1;}
+	
+	[ -z "$STATIC_STRUCTURE_FILE" ] || { echo >&2 "Error: static structure file provided in pre-docked mode"; exit 1;}
+	
+	[ -z "$MOBILE_STRUCTURE_FILE" ] || { echo >&2 "Error: mobile structure file not provided in pre-docked mode"; exit 1;}
+	
+	DOCKING_REGIME="pre-docked"
+else
+	if [ -n "$SYMMETRY_DOCKING" ]
+	then
+		[ -z "$STATIC_STRUCTURE_FILE" ] || { echo >&2 "Error: static structure file provided in homo docking mode"; exit 1;}
+		
+		[ -n "$MOBILE_STRUCTURE_FILE" ] || { echo >&2 "Error: mobile structure file not provided in homo docking mode"; exit 1;}
+		[ -s "$MOBILE_STRUCTURE_FILE" ] || { echo >&2 "Error: mobile structure file non-existing or empty in homo docking mode"; exit 1;}
+		[ -n "$MOBILE_STRUCTURE_SELECTION" ] || { echo >&2 "Error: mobile structure selection not defined in homo docking mode"; exit 1;}
+		
+		DOCKING_REGIME="homo"
+	else
+		[ -n "$STATIC_STRUCTURE_FILE" ] || { echo >&2 "Error: static structure file not provided in hetero docking mode"; exit 1;}
+		[ -s "$STATIC_STRUCTURE_FILE" ] || { echo >&2 "Error: static structure file non-existing or empty in hetero docking mode"; exit 1;}
+		[ -n "$STATIC_STRUCTURE_SELECTION" ] || { echo >&2 "Error: static structure selection not defined in hetero docking mode"; exit 1;}
+		
+		[ -n "$MOBILE_STRUCTURE_FILE" ] || { echo >&2 "Error: mobile structure file not provided in hetero docking mode"; exit 1;}
+		[ -s "$MOBILE_STRUCTURE_FILE" ] || { echo >&2 "Error: mobile structure file non-existing or empty in hetero docking mode"; exit 1;}
+		[ -n "$MOBILE_STRUCTURE_SELECTION" ] || { echo >&2 "Error: mobile structure selection not defined in hetero docking mode"; exit 1;}
+		
+		DOCKING_REGIME="hetero"
+	fi
+fi
 
 [ -n "$INTERFACE_SUBSELECTION" ] || { echo >&2 "Error: contacts subselection not defined"; exit 1; }
 
@@ -316,29 +370,59 @@ fi
 
 ################################################################################
 
-ftdmp-all-dock \
-  --job-name                "$JOB_NAME" \
-  --static-file             "$STATIC_STRUCTURE_FILE" \
-  --static-sel              "$STATIC_STRUCTURE_SELECTION" \
-  --static-chain            "$STATIC_STRUCTURE_CHAIN" \
-  --mobile-file             "$MOBILE_STRUCTURE_FILE" \
-  --mobile-sel              "$MOBILE_STRUCTURE_SELECTION" \
-  --mobile-chain            "$MOBILE_STRUCTURE_CHAIN" \
-  --openmm-forcefield       "$OPENMM_FORCEFIELD" \
-  --conda-path              "$CONDA_PATH" \
-  --conda-env               "$CONDA_ENV" \
-  --ftdock-keep             "$FTDOCK_KEEP" \
-  --ftdock-angle-step       "$FTDOCK_ANGLE_STEP" \
-  --min-grid-sep            "$MIN_GRID_SEP" \
-  --parallel                "$DOCKING_PROCESSORS" \
-  --sbatch                  "$DOCKING_SBATCH" \
-  --output-dir              "$OUTPUT_PATH"
-
 OUTPUT_PATH="${OUTPUT_PATH}/${JOB_NAME}"
 
-PREPARED_STATIC_STRUCTURE_FILE="${OUTPUT_PATH}/monomer_static.pdb"
+PREPARED_STATIC_STRUCTURE_FILE=""
+PREPARED_MOBILE_STRUCTURE_FILE=""
+INPUT_COMPLEX_PREFIX=""
+INPUT_COMPLEX_SUFFIX=""
 
-PREPARED_MOBILE_STRUCTURE_FILE="${OUTPUT_PATH}/monomer_mobile.pdb"
+if [ "$DOCKING_REGIME" == "hetero" ]
+then
+	ftdmp-all-dock \
+	  --job-name                "$JOB_NAME" \
+	  --static-file             "$STATIC_STRUCTURE_FILE" \
+	  --static-sel              "$STATIC_STRUCTURE_SELECTION" \
+	  --static-chain            "$STATIC_STRUCTURE_CHAIN" \
+	  --mobile-file             "$MOBILE_STRUCTURE_FILE" \
+	  --mobile-sel              "$MOBILE_STRUCTURE_SELECTION" \
+	  --mobile-chain            "$MOBILE_STRUCTURE_CHAIN" \
+	  --openmm-forcefield       "$OPENMM_FORCEFIELD" \
+	  --conda-path              "$CONDA_PATH" \
+	  --conda-env               "$CONDA_ENV" \
+	  --ftdock-keep             "$FTDOCK_KEEP" \
+	  --ftdock-angle-step       "$FTDOCK_ANGLE_STEP" \
+	  --min-grid-sep            "$MIN_GRID_SEP" \
+	  --parallel                "$DOCKING_PROCESSORS" \
+	  --sbatch                  "$DOCKING_SBATCH" \
+	  --output-dir              "$OUTPUT_PATH"
+
+	PREPARED_STATIC_STRUCTURE_FILE="${OUTPUT_PATH}/monomer_static.pdb"
+	
+	PREPARED_MOBILE_STRUCTURE_FILE="${OUTPUT_PATH}/monomer_mobile.pdb"
+fi
+
+if [ "$DOCKING_REGIME" == "homo" ]
+then
+	echo >&2 "Error: homo docking not enabled right now"
+	exit 1
+fi
+
+if [ "$DOCKING_REGIME" == "pre-docked" ]
+then
+	mkdir -p "$OUTPUT_PATH"
+	
+	{
+		echo "ID"
+		find "$PRE_DOCKED_INPUT_DIR" -type f -name '*.pdb' -not -empty \
+		| sed "s|^${PRE_DOCKED_INPUT_DIR}||" \
+		| sed 's|\.pdb$||'
+	} \
+	> "${OUTPUT_PATH}/docking_results.txt"
+	
+	INPUT_COMPLEX_PREFIX="${PRE_DOCKED_INPUT_DIR}"
+	INPUT_COMPLEX_SUFFIX=".pdb"
+fi
 
 PREV_SCORING_RESULTS_FILE="${OUTPUT_PATH}/docking_results.txt"
 
@@ -354,6 +438,8 @@ ftdmp-all-score \
   --input-from-table        "$PREV_SCORING_RESULTS_FILE" \
   --structure-monomer1      "$PREPARED_STATIC_STRUCTURE_FILE" \
   --structure-monomer2      "$PREPARED_MOBILE_STRUCTURE_FILE" \
+  --structure-prefix        "$INPUT_COMPLEX_PREFIX" \
+  --structure-suffix        "$INPUT_COMPLEX_SUFFIX" \
   --subselect-contacts      "$INTERFACE_SUBSELECTION" \
   --reference               "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" \
   --remap-cadscore          "$REMAP_CADSCORE" \
@@ -404,13 +490,15 @@ ftdmp-all-jury \
   --input-scoring-table     "$PREV_SCORING_RESULTS_FILE" \
   --structure-monomer1      "$PREPARED_STATIC_STRUCTURE_FILE" \
   --structure-monomer2      "$PREPARED_MOBILE_STRUCTURE_FILE" \
+  --structure-prefix        "$INPUT_COMPLEX_PREFIX" \
+  --structure-suffix        "$INPUT_COMPLEX_SUFFIX" \
   --subselect-contacts      "$INTERFACE_SUBSELECTION" \
   --rank-names              "$SCORING_RANKS" \
   --ranks-top               "$SCORING_TOP_STAGE2" \
   --remap-cadscore          "$REMAP_CADSCORE" \
   --jury-slices             "$SCORING_RANKS_JURY_SLICES" \
-  --jury-cluster            "0.9" \
-  --jury-max-values         "5" \
+  --jury-cluster            "$SCORING_RANKS_JURY_CLUSTER" \
+  --jury-max-values         "$SCORING_RANKS_JURY_MAX_VALUES" \
   --redundancy-threshold    "$REDUNDANCY_THRESHOLD" \
   --parallel                "$SCORING_PROCESSORS" \
   --sbatch                  "$SCORING_SBATCH" \
@@ -431,39 +519,76 @@ then
 	NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/raw_top_built_results.txt"
 	
 	TOP_COMPLEXES_DIR="${OUTPUT_PATH}/raw_top_complexes"
-	TOP_COMPLEXES_RAW_DIR="${OUTPUT_PATH}/raw_top_complexes_raw"
 	
-	{
-	cat "$PREV_SCORING_RESULTS_FILE"
-	cat "$PREPARED_STATIC_STRUCTURE_FILE"
-	cat "$PREPARED_MOBILE_STRUCTURE_FILE"
-	echo "$NUMBER_OF_COMPLEXES_TO_BUILD"
-	echo "$MULTIPLY_CHAINS"
-	} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
-	
-	if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
+	if [ "$DOCKING_REGIME" == "hetero" ]
 	then
-		rm -rf "$TOP_COMPLEXES_DIR"
-		rm -rf "$TOP_COMPLEXES_RAW_DIR"
+		TOP_COMPLEXES_RAW_DIR="${OUTPUT_PATH}/raw_top_complexes_raw"
 		
-		cat "$PREV_SCORING_RESULTS_FILE" \
-		| head -n "$((NUMBER_OF_COMPLEXES_TO_BUILD+1))" \
-		| ftdmp-build-complex --monomer1 "$PREPARED_STATIC_STRUCTURE_FILE" --monomer2 "$PREPARED_MOBILE_STRUCTURE_FILE" \
-		  --output-prefix "${TOP_COMPLEXES_DIR}/" \
-		  --output-suffix ".pdb" \
-		> "$NEXT_SCORING_RESULTS_FILE"
+		{
+		cat "$PREV_SCORING_RESULTS_FILE"
+		cat "$PREPARED_STATIC_STRUCTURE_FILE"
+		cat "$PREPARED_MOBILE_STRUCTURE_FILE"
+		echo "$NUMBER_OF_COMPLEXES_TO_BUILD"
+		echo "$MULTIPLY_CHAINS"
+		} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
 		
-		if [ -n "$MULTIPLY_CHAINS" ]
+		if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
 		then
-			mv "$TOP_COMPLEXES_DIR" "$TOP_COMPLEXES_RAW_DIR"
-			
-			cat "$NEXT_SCORING_RESULTS_FILE" \
-			| tail -n +2 \
-			| awk -v inputprefix="${TOP_COMPLEXES_RAW_DIR}/" -v outputprefix="${TOP_COMPLEXES_DIR}/" -v suffix=".pdb" \
-			  '{print inputprefix $1 suffix " " outputprefix $1 suffix}' \
-			| xargs -L 1 -P "$SCORING_PROCESSORS" bash -c "ftdmp-multiply-chains $MULTIPLY_CHAINS --input \$0 --output \$1"
-			
+			rm -rf "$TOP_COMPLEXES_DIR"
 			rm -rf "$TOP_COMPLEXES_RAW_DIR"
+			
+			cat "$PREV_SCORING_RESULTS_FILE" \
+			| head -n "$((NUMBER_OF_COMPLEXES_TO_BUILD+1))" \
+			| ftdmp-build-complex --monomer1 "$PREPARED_STATIC_STRUCTURE_FILE" --monomer2 "$PREPARED_MOBILE_STRUCTURE_FILE" \
+			  --output-prefix "${TOP_COMPLEXES_DIR}/" \
+			  --output-suffix ".pdb" \
+			> "$NEXT_SCORING_RESULTS_FILE"
+			
+			if [ -n "$MULTIPLY_CHAINS" ]
+			then
+				mv "$TOP_COMPLEXES_DIR" "$TOP_COMPLEXES_RAW_DIR"
+				
+				cat "$NEXT_SCORING_RESULTS_FILE" \
+				| tail -n +2 \
+				| awk -v inputprefix="${TOP_COMPLEXES_RAW_DIR}/" -v outputprefix="${TOP_COMPLEXES_DIR}/" -v suffix=".pdb" \
+				  '{print inputprefix $1 suffix " " outputprefix $1 suffix}' \
+				| xargs -L 1 -P "$SCORING_PROCESSORS" bash -c "ftdmp-multiply-chains $MULTIPLY_CHAINS --input \$0 --output \$1"
+				
+				rm -rf "$TOP_COMPLEXES_RAW_DIR"
+			fi
+		fi
+	fi
+	
+	if [ "$DOCKING_REGIME" == "hetero" ] || [ "$DOCKING_REGIME" == "pre-docked" ]
+	then
+		{
+		cat "$PREV_SCORING_RESULTS_FILE"
+		echo "$NUMBER_OF_COMPLEXES_TO_BUILD"
+		} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
+		
+		if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
+		then
+			rm -rf "$TOP_COMPLEXES_DIR"
+			
+			cat "$PREV_SCORING_RESULTS_FILE" \
+			| ftdmp-extract-table-columns ID \
+			| tail -n +2 \
+			| head -n "$NUMBER_OF_COMPLEXES_TO_BUILD" \
+			| while read -r IDTOCOPY
+			do
+				mkdir -p "$(dirname ${TOP_COMPLEXES_DIR}/${IDTOCOPY})"
+				cp "${INPUT_COMPLEX_PREFIX}${IDTOCOPY}${INPUT_COMPLEX_SUFFIX}" "${TOP_COMPLEXES_DIR}/${IDTOCOPY}.pdb"
+			done
+			
+			if [ "$(find $TOP_COMPLEXES_DIR -type f -name '*.pdb' -not -empty | wc -l)" -ne "$NUMBER_OF_COMPLEXES_TO_BUILD" ]
+			then
+				echo >&2 "Error: failed to copy all top complexes"
+				exit 1
+			fi
+			
+			cat "$PREV_SCORING_RESULTS_FILE" \
+			| head -n "$((NUMBER_OF_COMPLEXES_TO_BUILD+1))" \
+			> "$NEXT_SCORING_RESULTS_FILE"
 		fi
 	fi
 	
@@ -500,6 +625,12 @@ do
 		| bash
 	fi
 done
+
+if [ "$(find $TOP_RELAXED_COMPLEXES_DIR -type f -name '*.pdb' -not -empty | wc -l)" -ne "$NUMBER_OF_COMPLEXES_TO_BUILD" ]
+then
+	echo >&2 "Error: failed to relax all top complexes"
+	exit 1
+fi
 
 ################################################################################
 
@@ -543,14 +674,14 @@ ftdmp-all-jury \
   --ranks-top               "999999" \
   --remap-cadscore          "$REMAP_CADSCORE" \
   --jury-slices             "$SCORING_RANKS_JURY_SLICES" \
-  --jury-cluster            "0.9" \
-  --jury-max-values         "5" \
+  --jury-cluster            "$SCORING_RANKS_JURY_CLUSTER" \
+  --jury-max-values         "$SCORING_RANKS_JURY_MAX_VALUES" \
   --redundancy-threshold    "$REDUNDANCY_THRESHOLD" \
   --parallel                "$SCORING_PROCESSORS" \
   --sbatch                  "$SCORING_SBATCH" \
   --output-names-prefix     "relaxed_"
 
-PREV_SCORING_RESULTS_FILE="${OUTPUT_PATH}/relaxed_top_scoring_results.txt"
+PREV_SCORING_RESULTS_FILE="${OUTPUT_PATH}/relaxed_top_scoring_results_RJS.txt"
 
 if [ ! -s "$PREV_SCORING_RESULTS_FILE" ]
 then
