Simplified main pipeline.

diff --git a/ftdmp-all b/ftdmp-all
--- a/ftdmp-all
+++ b/ftdmp-all
@@ -365,6 +365,11 @@ then
 	SCORING_RANKS="raw_FIV_iface_energy_rank  raw_FIV_energy_clash_tour_rank  raw_FIVb_iface_energy_rank  raw_FIVb_energy_clash_tour_rank  raw_FIGNN_sum_of_gnn_scores_rank  raw_FIGNN_average_gnn_score_rank  raw_FIGNN_weighted_average_pcadscore_rank  raw_FIV_and_FGV_light_tour_rank  raw_FIV_and_FGV_dark_tour_rank  raw_FIGNN_and_FGV_light_tour_rank  raw_FIGNN_and_FGV_dark_tour_rank"
 fi
 
+if [ "$SCORING_RANKS" == "modern_for_protein_protein" ]
+then
+	SCORING_RANKS="raw_FIV_iface_energy_rank  raw_FIGNN_sum_of_gnn_scores_rank"
+fi
+
 SCORING_MODE_PROTEIN="false"
 SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT="false"
 SCORING_MODE_GENERIC="false"
@@ -491,81 +496,38 @@ fi
 
 ################################################################################
 
-if [ "$SCORING_MODE_PROTEIN" == "true" ] || [ "$SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT" == "true" ] || [ "$SCORING_MODE_GENERIC" == "true" ] || [ "$SCORING_MODE_GENERIC_SIDECHAIN_REBUILT" == "true" ]
-then
-	ftdmp-all-score \
-	  --input-from-table        "$PREV_SCORING_RESULTS_FILE" \
-	  --structure-monomer1      "$PREPARED_STATIC_STRUCTURE_FILE" \
-	  --structure-monomer2      "$PREPARED_MOBILE_STRUCTURE_FILE" \
-	  --structure-prefix        "$INPUT_COMPLEX_PREFIX" \
-	  --structure-suffix        "$INPUT_COMPLEX_SUFFIX" \
-	  --subselect-contacts      "$INTERFACE_SUBSELECTION" \
-	  --reference               "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" \
-	  --remap-cadscore          "$REMAP_CADSCORE" \
-	  --mode-protein            "$SCORING_MODE_PROTEIN" \
-	  --mode-protein-sr         "$SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT" \
-	  --mode-generic            "$SCORING_MODE_GENERIC" \
-	  --mode-generic-sr         "$SCORING_MODE_GENERIC_SIDECHAIN_REBUILT" \
-	  --score-symmetry          "$SCORE_SYMMETRY" \
-	  --keep-top                "$SCORING_TOP_STAGE1" \
-	  --clash-tour-tolerance    "0.05" \
-	  --parallel                "$SCORING_PROCESSORS" \
-	  --sbatch                  "$SCORING_SBATCH" \
-	  --output-names-prefix     "raw_" \
-	  --last-output-suffix      "_faster" \
-	  --output-dir              "$OUTPUT_PATH"
-	
-	PREV_SCORING_RESULTS_FILE="${OUTPUT_PATH}/raw_scoring_results_with_ranks_faster.txt"
-	
-	if [ ! -s "$PREV_SCORING_RESULTS_FILE" ]
-	then
-		echo >&2 "Error: no raw scoring results after faster scoring"
-		exit 1
-	fi
-fi
+ftdmp-all-score \
+  --input-from-table        "$PREV_SCORING_RESULTS_FILE" \
+  --structure-monomer1      "$PREPARED_STATIC_STRUCTURE_FILE" \
+  --structure-monomer2      "$PREPARED_MOBILE_STRUCTURE_FILE" \
+  --structure-prefix        "$INPUT_COMPLEX_PREFIX" \
+  --structure-suffix        "$INPUT_COMPLEX_SUFFIX" \
+  --subselect-contacts      "$INTERFACE_SUBSELECTION" \
+  --reference               "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" \
+  --remap-cadscore          "$REMAP_CADSCORE" \
+  --mode-protein            "$SCORING_MODE_PROTEIN" \
+  --mode-protein-sr         "$SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT" \
+  --mode-generic            "$SCORING_MODE_GENERIC" \
+  --mode-generic-sr         "$SCORING_MODE_GENERIC_SIDECHAIN_REBUILT" \
+  --mode-protein-gnn        "$SCORING_MODE_PROTEIN_GNN" \
+  --mode-protein-gnn-sr     "$SCORING_MODE_PROTEIN_GNN_SIDECHAIN_REBUILT" \
+  --mode-protein-global     "$SCORING_MODE_PROTEIN_GLOBAL" \
+  --conda-path              "$CONDA_PATH" \
+  --conda-env               "$CONDA_ENV_FOR_GNN" \
+  --score-symmetry          "$SCORE_SYMMETRY" \
+  --keep-top                "$SCORING_TOP_STAGE1" \
+  --clash-tour-tolerance    "0.05" \
+  --parallel                "$SCORING_PROCESSORS" \
+  --sbatch                  "$SCORING_SBATCH" \
+  --output-names-prefix     "raw_" \
+  --output-dir              "$OUTPUT_PATH"
 
-################################################################################
+PREV_SCORING_RESULTS_FILE="${OUTPUT_PATH}/raw_scoring_results_with_ranks.txt"
 
-if [ "$SCORING_MODE_PROTEIN_GNN" == "true" ] || [ "$SCORING_MODE_PROTEIN_GNN_SIDECHAIN_REBUILT" == "true" ] || [ "$SCORING_MODE_PROTEIN_GLOBAL" == "true" ]
+if [ ! -s "$PREV_SCORING_RESULTS_FILE" ]
 then
-	NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/raw_scoring_results_with_ranks_faster_shortened.txt"
-	
-	ONLY_FASTER_SCORING_RANKS="$(echo $SCORING_RANKS | sed 's/\s\+/\n/g' | grep -v '_FIGNN_' | grep -v '_FGV_' | tr '\n' ' ')"
-	
-	cat "$PREV_SCORING_RESULTS_FILE" \
-	| ftdmp-filter-table \
-	  "<=${SCORING_TOP_STAGE2}" $ONLY_FASTER_SCORING_RANKS \
-	> "$NEXT_SCORING_RESULTS_FILE"
-	
-	PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"
-	
-	ftdmp-all-score \
-	  --input-from-table        "$PREV_SCORING_RESULTS_FILE" \
-	  --structure-monomer1      "$PREPARED_STATIC_STRUCTURE_FILE" \
-	  --structure-monomer2      "$PREPARED_MOBILE_STRUCTURE_FILE" \
-	  --structure-prefix        "$INPUT_COMPLEX_PREFIX" \
-	  --structure-suffix        "$INPUT_COMPLEX_SUFFIX" \
-	  --subselect-contacts      "$INTERFACE_SUBSELECTION" \
-	  --mode-protein-gnn        "$SCORING_MODE_PROTEIN_GNN" \
-	  --mode-protein-gnn-sr     "$SCORING_MODE_PROTEIN_GNN_SIDECHAIN_REBUILT" \
-	  --mode-protein-global     "$SCORING_MODE_PROTEIN_GLOBAL" \
-	  --conda-path              "$CONDA_PATH" \
-	  --conda-env               "$CONDA_ENV_FOR_GNN" \
-	  --keep-top                "$SCORING_TOP_STAGE1" \
-	  --clash-tour-tolerance    "0.05" \
-	  --parallel                "$SCORING_PROCESSORS" \
-	  --sbatch                  "$SCORING_SBATCH" \
-	  --output-names-prefix     "raw_" \
-	  --last-output-suffix      "_slower" \
-	  --output-dir              "$OUTPUT_PATH"
-	
-	PREV_SCORING_RESULTS_FILE="${OUTPUT_PATH}/raw_scoring_results_with_ranks_slower.txt"
-	
-	if [ ! -s "$PREV_SCORING_RESULTS_FILE" ]
-	then
-		echo >&2 "Error: no raw scoring results after slower scoring"
-		exit 1
-	fi
+	echo >&2 "Error: no raw scoring results"
+	exit 1
 fi
 
 ################################################################################
