Updated core.

diff --git a/core/voronota-iface-gnn_release/voronota-iface-gnn-score b/core/voronota-iface-gnn_release/voronota-iface-gnn-score
--- a/core/voronota-iface-gnn_release/voronota-iface-gnn-score
+++ b/core/voronota-iface-gnn_release/voronota-iface-gnn-score
@@ -23,6 +23,8 @@ Options:
     --local-column            string     flag to add per-residue scores to the global output table
     --cache-dir               string     cache directory path to store results of past calls
     --output-dir              string     output directory path for all results
+    --output-pdb-file         string     output path for PDB file with interface residue scores, default is ''
+    --output-pdb-mode         string     mode to write b-factors ('overwrite_all', 'overwrite_iface' or 'combine'), default is 'overwrite_all'
     --help | -h                          flag to display help message and exit
 
 Standard output:
@@ -41,6 +43,17 @@ Requirements installation example using Miniconda (needs about 9 GB of disk spac
 
 EOF
 exit 1
+}
+
+################################################################################
+
+function substitute_id_in_filename
+{
+	SUBSTITUTE_BASENAME="$(basename "$1")"
+	SUBSTITUTE_TEMPLATE="$2"
+	
+	echo "$SUBSTITUTE_TEMPLATE" \
+	| sed "s|-BASENAME-|${SUBSTITUTE_BASENAME}|"
 }
 
 ################################################################################
@@ -79,6 +92,9 @@ SBATCH_PARAMETERS=""
 LOCAL_COLUMN="false"
 CACHE_DIR=""
 OUTDIR=""
+OUTPUT_PDB_FILE=""
+OUTPUT_PDB_MODE="overwrite_all"
+JUST_OUTPUT_FROM_DIR=""
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -151,6 +167,18 @@ do
 		OUTDIR="$OPTARG"
 		shift
 		;;
+	--output-pdb-file)
+		OUTPUT_PDB_FILE="$OPTARG"
+		shift
+		;;
+	--output-pdb-mode)
+		OUTPUT_PDB_MODE="$OPTARG"
+		shift
+		;;
+	--jofd)
+		JUST_OUTPUT_FROM_DIR="$OPTARG"
+		shift
+		;;
 	-h|--help)
 		HELP_MODE="true"
 		;;
@@ -178,7 +206,168 @@ then
 	exit 1
 fi
 
+if [ -n "$OUTPUT_PDB_FILE" ] && [ "$OUTPUT_PDB_MODE" != "overwrite_all" ] && [ "$OUTPUT_PDB_MODE" != "overwrite_iface" ] && [ "$OUTPUT_PDB_MODE" != "combine" ]
+then
+	echo >&2 "Error: invalid mode for PDB output"
+	exit 1
+fi
+
 INFILENAME="$(basename $INFILE)"
+OUTDIR="$(substitute_id_in_filename "$INFILENAME" "$OUTDIR")"
+OUTPUT_PDB_FILE="$(substitute_id_in_filename "$INFILENAME" "$OUTPUT_PDB_FILE")"
+
+################################################################################
+
+if [ -n "$JUST_OUTPUT_FROM_DIR" ]
+then
+	{
+		if [ "$LOCAL_COLUMN" == "true" ]
+		then
+			cat "$JUST_OUTPUT_FROM_DIR/results_summary_table_with_local_column.txt"
+		else
+			cat "$JUST_OUTPUT_FROM_DIR/results_summary_table.txt"
+		fi
+	} \
+	| sed '1 s|^|input_name |' \
+	| sed "2 s|^|${INFILENAME} |" \
+	| column -t \
+	| {
+		if [ -n "$OUTDIR" ]
+		then
+			mkdir -p "$OUTDIR"
+			cat > "${OUTDIR}/${INFILENAME}__gnn_scores_global.txt"
+			cat "$JUST_OUTPUT_FROM_DIR/results_per_contact.txt" > "${OUTDIR}/${INFILENAME}__gnn_scores_per_contact.txt"
+			cat "$JUST_OUTPUT_FROM_DIR/results_per_residue.txt" > "${OUTDIR}/${INFILENAME}__gnn_scores_per_residue.txt"
+			cat "${OUTDIR}/${INFILENAME}__gnn_scores_global.txt"
+		else 
+			cat
+		fi
+	}
+	
+	if [ -n "$OUTPUT_PDB_FILE" ]
+	then
+		if [ -n "$OUTPUT_PDB_FILE" ]
+		then
+			mkdir -p "$(dirname $OUTPUT_PDB_FILE)"
+		fi
+		
+{
+cat << EOF
+var common_params={}
+common_params.input_is_script='$INPUT_IS_SCRIPT';
+common_params.input_as_assembly='$AS_ASSEMBLY';
+common_params.restrict_input_atoms='$RESTRICT_INPUT';
+common_params.output_pdb_file='$OUTPUT_PDB_FILE';
+common_params.output_pdb_mode='$OUTPUT_PDB_MODE';
+var input_info={"input_file": "$INFILE", "input_file_name": "$INFILENAME", "input_adjuncts_file": "$JUST_OUTPUT_FROM_DIR/results_per_residue.txt"}
+EOF
+
+cat << 'EOF'
+analyze_structure=function(params, input)
+{
+
+if(input.input_file===undefined || input.input_file==="")
+{
+	throw ("No input file");
+}
+
+if(input.input_adjuncts_file===undefined || input.input_adjuncts_file==="")
+{
+	throw ("No input adjuncts file");
+}
+
+if(params.output_pdb_file===undefined || params.output_pdb_file==="")
+{
+	throw ("No output file path file");
+}
+
+if(params.output_pdb_mode!="overwrite_all" && params.output_pdb_mode!="overwrite_iface" && params.output_pdb_mode!="combine")
+{
+	throw ("Invalid mode for PDB output");
+}
+
+if(params.input_is_script===undefined || params.input_is_script==="")
+{
+	params.input_is_script="false";
+}
+
+if(params.input_as_assembly===undefined || params.input_as_assembly==="")
+{
+	params.input_as_assembly="false";
+}
+
+if(params.restrict_input_atoms===undefined || params.restrict_input_atoms==="")
+{
+	params.restrict_input_atoms='[]';
+}
+
+voronota_delete_objects();
+
+if(params.input_is_script=="true")
+{
+	voronota_source("-file", input.input_file);
+	voronota_assert_partial_success("Failed when running provided input script");
+}
+else
+{
+	voronota_import("-file", input.input_file, "-as-assembly", params.input_as_assembly);
+	voronota_assert_partial_success("Failed to import file");
+}
+
+voronota_restrict_atoms("-use", params.restrict_input_atoms);
+voronota_assert_full_success("Failed to restrict input atoms by the input query");
+
+voronota_import_adjuncts_of_atoms("-file", input.input_adjuncts_file);
+voronota_assert_full_success("Failed to import adjuncts");
+
+if(params.output_pdb_mode=="overwrite_all")
+{
+	voronota_set_adjunct_of_atoms("-use", "[-adjuncts-not pcadscore]", "-name", "pcadscore", "-value", 1.0);
+	
+	voronota_set_adjunct_of_atoms_by_expression("-use", "[-adjuncts pcadscore]", "-expression", "_linear_combo", "-input-adjuncts", "pcadscore", "-parameters", [100, 0], "-output-adjunct", "tf");
+	voronota_assert_full_success("Failed to set output adjuncts");
+}
+
+if(params.output_pdb_mode=="overwrite_iface")
+{
+	voronota_set_adjunct_of_atoms_by_expression("-use", "[-adjuncts pcadscore]", "-expression", "_linear_combo", "-input-adjuncts", "pcadscore", "-parameters", [100, 0], "-output-adjunct", "tf");
+	voronota_assert_full_success("Failed to set output adjuncts");
+}
+
+if(params.output_pdb_mode=="combine")
+{
+	voronota_set_adjunct_of_atoms_by_expression("-use", "[-adjuncts pcadscore]", "-expression", "_linear_combo", "-input-adjuncts", "pcadscore", "-parameters", [100, 0], "-output-adjunct", "pcadscore100");
+	voronota_assert_full_success("Failed to transform adjuncts");
+	
+	voronota_set_adjunct_of_atoms_by_expression("-use", "[-adjuncts pcadscore100]", "-expression", "_multiply", "-input-adjuncts", ["pcadscore100", "tf"], "-output-adjunct", "combo_product");
+	voronota_assert_full_success("Failed to multiply adjuncts");
+	
+	voronota_set_adjunct_of_atoms_by_expression("-use", "[-adjuncts combo_product]", "-expression", "_sqrt", "-input-adjuncts", "combo_product", "-output-adjunct", "tf");
+	voronota_assert_full_success("Failed to sqrt adjuncts");
+}
+
+voronota_export_atoms("-file", params.output_pdb_file, "-as-pdb", "-pdb-b-factor", "tf", "-pdb-ter");
+voronota_assert_full_success("Failed to export atoms with adjuncts");
+}
+
+try
+{
+	analyze_structure(common_params, input_info);
+}
+catch(error)
+{
+	log("Failed with '"+input_info.input_file_name+"': "+error);
+}
+
+EOF
+} \
+| voronota-js --no-setup-defaults
+	fi
+	
+	exit 0
+fi
+
+################################################################################
 
 if [ -z "$GNN_PACKAGE_FILES" ]
 then
@@ -212,7 +401,12 @@ then
 	{
 		echo "$RESTRICT_INPUT $AS_ASSEMBLY $INPUT_IS_SCRIPT $SUBSELECT_CONTACTS $RUN_FASPR"
 		
-		cat "$INFILE"
+		if [ "$INPUT_IS_SCRIPT" == "true" ]
+		then
+			cat "$INFILE"
+		else
+			cat "$INFILE" | egrep '^ATOM ' | cut -c 1-60 | sed 's/\s\+/ /g' | sed 's/\s\+$//'
+		fi
 		
 		echo "$GNN_PACKAGE_FILES" \
 		| sed 's|\s\+|\n|g' \
@@ -248,28 +442,7 @@ then
 			exit 1
 		fi
 		
-		{
-			if [ "$LOCAL_COLUMN" == "true" ]
-			then
-				cat "${TMPLDIR}/saved_results/results_summary_table_with_local_column.txt"
-			else
-				cat "${TMPLDIR}/saved_results/results_summary_table.txt"
-			fi
-		} \
-		| sed '1 s|^|input_name |' \
-		| sed "2 s|^|${INFILENAME} |" \
-		| column -t \
-		> "${TMPLDIR}/saved_results/display_summary_table.txt"
-		
-		cat "${TMPLDIR}/saved_results/display_summary_table.txt"
-		
-		if [ -n "$OUTDIR" ]
-		then
-			mkdir -p "$OUTDIR"
-			mv "${TMPLDIR}/saved_results/display_summary_table.txt" "${OUTDIR}/${INFILENAME}__gnn_scores_global.txt"
-			mv "${TMPLDIR}/saved_results/results_per_contact.txt" "${OUTDIR}/${INFILENAME}__gnn_scores_per_contact.txt"
-			mv "${TMPLDIR}/saved_results/results_per_residue.txt" "${OUTDIR}/${INFILENAME}__gnn_scores_per_residue.txt"
-		fi
+		"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR/saved_results"
 		
 		exit 0
 	fi
@@ -523,36 +696,15 @@ then
 	tar -czf "${HASHSUM}.tar.gz" "./results_summary_table.txt" "./results_summary_table_with_local_column.txt" "./results_per_contact.txt" "./results_per_residue.txt"
 fi
 
-{
-	if [ "$LOCAL_COLUMN" == "true" ]
-	then
-		cat "./results_summary_table_with_local_column.txt"
-	else
-		cat "./results_summary_table.txt"
-	fi
-} \
-| sed '1 s|^|input_name |' \
-| sed "2 s|^|${INFILENAME} |" \
-| column -t \
-> "./display_summary_table.txt"
-
-cat "./display_summary_table.txt"
-
 cd - &> /dev/null
-
-if [ -n "$OUTDIR" ]
-then
-	mkdir -p "$OUTDIR"
-	mv "${TMPLDIR}/display_summary_table.txt" "${OUTDIR}/${INFILENAME}__gnn_scores_global.txt"
-	mv "${TMPLDIR}/results_per_contact.txt" "${OUTDIR}/${INFILENAME}__gnn_scores_per_contact.txt"
-	mv "${TMPLDIR}/results_per_residue.txt" "${OUTDIR}/${INFILENAME}__gnn_scores_per_residue.txt"
-fi
 
 if [ -n "$CACHE_DIR" ] && [ -n "$HASHSUM" ]
 then
 	mkdir -p "$CACHE_DIR"
 	mv "${TMPLDIR}/${HASHSUM}.tar.gz" "$CACHE_DIR/${HASHSUM}.tar.gz"
 fi
+
+"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR"
 
 exit 0
 
diff --git a/core/voronota-js_release/voronota-js-only-global-voromqa b/core/voronota-js_release/voronota-js-only-global-voromqa
--- a/core/voronota-js_release/voronota-js-only-global-voromqa
+++ b/core/voronota-js_release/voronota-js-only-global-voromqa
@@ -10,6 +10,8 @@ Options:
     --input | -i              string  *  input file path or '_list' to read file paths from stdin
     --restrict-input          string     query to restrict input atoms, default is '[]'
     --output-table-file       string     output table file path, default is '_stdout' to print to stdout
+    --output-dark-pdb         string     output path for PDB file with VoroMQA-dark scores, default is ''
+    --output-light-pdb        string     output path for PDB file with VoroMQA-light scores, default is ''
     --processors              number     maximum number of processors to run in parallel, default is 1
     --sbatch-parameters       string     sbatch parameters to run in parallel, default is ''
     --cache-dir               string     cache directory path to store results of past calls
@@ -60,12 +62,15 @@ command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executab
 INFILE=""
 RESTRICT_INPUT="[]"
 OUTPUT_TABLE_FILE="_stdout"
+OUTPUT_DARK_PDB=""
+OUTPUT_LIGHT_PDB=""
 MAX_PROCESSORS="1"
 SBATCH_PARAMETERS=""
 CACHE_DIR=""
 RUN_FASPR=""
 INPUT_IS_SCRIPT="false"
 AS_ASSEMBLY="false"
+JUST_OUTPUT_FROM_DIR=""
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -84,6 +89,14 @@ do
 		;;
 	--output-table-file)
 		OUTPUT_TABLE_FILE="$OPTARG"
+		shift
+		;;
+	--output-dark-pdb)
+		OUTPUT_DARK_PDB="$OPTARG"
+		shift
+		;;
+	--output-light-pdb)
+		OUTPUT_LIGHT_PDB="$OPTARG"
 		shift
 		;;
 	--processors)
@@ -107,6 +120,10 @@ do
 		;;
 	--as-assembly)
 		AS_ASSEMBLY="true"
+		;;
+	--jofd)
+		JUST_OUTPUT_FROM_DIR="$OPTARG"
+		shift
 		;;
 	-h|--help)
 		HELP_MODE="true"
@@ -139,6 +156,156 @@ if [ -n "$RUN_FASPR" ] && [ ! -s "$RUN_FASPR" ]
 then
 	echo >&2 "Error: FASPR binary executable file '$RUN_FASPR' does not exist"
 	exit 1
+fi
+
+INFILE_BASENAME="$(basename $INFILE)"
+OUTPUT_TABLE_FILE="$(substitute_id_in_filename "$INFILE_BASENAME" "$OUTPUT_TABLE_FILE")"
+OUTPUT_DARK_PDB="$(substitute_id_in_filename "$INFILE_BASENAME" "$OUTPUT_DARK_PDB")"
+OUTPUT_LIGHT_PDB="$(substitute_id_in_filename "$INFILE_BASENAME" "$OUTPUT_LIGHT_PDB")"
+
+if [ -n "$JUST_OUTPUT_FROM_DIR" ]
+then
+	cat "$JUST_OUTPUT_FROM_DIR/results_summary_table.txt" \
+	| sed '1 s|^|input_name |' \
+	| sed "2 s|^|${INFILE_BASENAME} |" \
+	| {
+		if [ "$OUTPUT_TABLE_FILE" == "_stdout" ]
+		then
+			cat
+		else
+			mkdir -p "$(dirname $OUTPUT_TABLE_FILE)"
+			cat > "$OUTPUT_TABLE_FILE"
+		fi
+	}
+	
+	if [ -n "$OUTPUT_DARK_PDB" ] || [ -n "$OUTPUT_LIGHT_PDB" ]
+	then
+		if [ -n "$OUTPUT_DARK_PDB" ]
+		then
+			mkdir -p "$(dirname $OUTPUT_DARK_PDB)"
+		fi
+		
+		if [ -n "$OUTPUT_LIGHT_PDB" ]
+		then
+			mkdir -p "$(dirname $OUTPUT_LIGHT_PDB)"
+		fi
+		
+{
+cat << EOF
+var common_params={}
+common_params.input_is_script='$INPUT_IS_SCRIPT';
+common_params.input_as_assembly='$AS_ASSEMBLY';
+common_params.restrict_input_atoms='$RESTRICT_INPUT';
+common_params.run_faspr='$RUN_FASPR';
+common_params.output_dark_pdb='$OUTPUT_DARK_PDB';
+common_params.output_light_pdb='$OUTPUT_LIGHT_PDB';
+var input_info={"input_file": "$INFILE", "input_file_name": "$INFILE_BASENAME", "input_adjuncts_file": "$JUST_OUTPUT_FROM_DIR/results_residue_scores.txt"}
+EOF
+
+cat << 'EOF'
+analyze_structure=function(params, input)
+{
+
+if(input.input_file===undefined || input.input_file==="")
+{
+	throw ("No input file");
+}
+
+if(input.input_adjuncts_file===undefined || input.input_adjuncts_file==="")
+{
+	throw ("No input adjuncts file");
+}
+
+if(params.input_is_script===undefined || params.input_is_script==="")
+{
+	params.input_is_script="false";
+}
+
+if(params.input_as_assembly===undefined || params.input_as_assembly==="")
+{
+	params.input_as_assembly="false";
+}
+
+if(params.restrict_input_atoms===undefined || params.restrict_input_atoms==="")
+{
+	params.restrict_input_atoms='[]';
+}
+
+if(params.run_faspr===undefined)
+{
+	params.run_faspr="";
+}
+
+if(params.output_dark_pdb===undefined)
+{
+	params.output_dark_pdb="";
+}
+
+if(params.output_light_pdb===undefined)
+{
+	params.output_light_pdb="";
+}
+
+voronota_delete_objects();
+
+if(params.input_is_script=="true")
+{
+	voronota_source("-file", input.input_file);
+	voronota_assert_partial_success("Failed when running provided input script");
+}
+else
+{
+	voronota_import("-file", input.input_file, "-as-assembly", params.input_as_assembly);
+	voronota_assert_partial_success("Failed to import file");
+}
+
+voronota_restrict_atoms("-use", params.restrict_input_atoms);
+voronota_assert_full_success("Failed to restrict input atoms by the input query");
+
+if(params.run_faspr!="")
+{
+	voronota_run_faspr("-faspr-binary", params.run_faspr);
+	voronota_assert_full_success("Failed to run FASPR");
+}
+
+voronota_import_adjuncts_of_atoms("-file", input.input_adjuncts_file);
+voronota_assert_full_success("Failed to import adjuncts");
+
+if(params.output_dark_pdb!="")
+{
+	voronota_set_adjunct_of_atoms_by_expression("-use", "[-adjuncts vd1_rs0]", "-expression", "_linear_combo", "-input-adjuncts", "vd1_rs0", "-parameters", [100, 0], "-output-adjunct", "vd1_rs0_100");
+	voronota_assert_full_success("Failed to set output dark adjuncts");
+	
+	voronota_export_atoms("-file", params.output_dark_pdb, "-as-pdb", "-pdb-b-factor", "vd1_rs0_100", "-pdb-ter");
+	voronota_assert_full_success("Failed to export atoms with dark adjuncts");
+}
+
+if(params.output_light_pdb!="")
+{
+	voronota_set_adjunct_of_atoms_by_expression("-use", "[-adjuncts voromqa_score_rs0]", "-expression", "_linear_combo", "-input-adjuncts", "voromqa_score_rs0", "-parameters", [100, 0], "-output-adjunct", "voromqa_score_rs0_100");
+	voronota_assert_full_success("Failed to set output light adjuncts");
+	
+	voronota_export_atoms("-file", params.output_light_pdb, "-as-pdb", "-pdb-b-factor", "voromqa_score_rs0_100", "-pdb-ter");
+	voronota_assert_full_success("Failed to export atoms with light adjuncts");
+}
+
+}
+
+try
+{
+	analyze_structure(common_params, input_info);
+}
+catch(error)
+{
+	log("Failed with '"+input_info.input_file_name+"': "+error);
+}
+
+EOF
+} \
+| voronota-js --no-setup-defaults
+	fi
+	
+	exit 0
 fi
 
 if [ -z "$MAX_PROCESSORS" ] || [ "$MAX_PROCESSORS" -ne "$MAX_PROCESSORS" ] || [ "$MAX_PROCESSORS" -lt "1" ]
@@ -180,7 +347,7 @@ fi
 
 if [ "$INFILE" == "_list" ]
 then	
-	cat | egrep . | egrep -v '^_list$' | sort | uniq > "$TMPLDIR/input_list"
+	cat | egrep . | sort | uniq > "$TMPLDIR/input_list"
 	
 	if [ ! -s "$TMPLDIR/input_list" ]
 	then
@@ -228,37 +395,44 @@ then
 	exit 0
 fi
 
-INFILE_BASENAME="$(basename $INFILE)"
-OUTPUT_TABLE_FILE="$(substitute_id_in_filename "$INFILE_BASENAME" "$OUTPUT_TABLE_FILE")"
-
 HASHSUM=""
 
-if [ -n "$CACHE_DIR" ] && [ "$INFILE" != "_list" ]
+if [ -n "$CACHE_DIR" ]
 then
 	{
 		echo "$RESTRICT_INPUT $AS_ASSEMBLY $INPUT_IS_SCRIPT"
+		
 		[ -z "$RUN_FASPR" ] || { echo "with_faspr"; }
-		cat "$INFILE"
+		
+		if [ "$INPUT_IS_SCRIPT" == "true" ]
+		then
+			cat "$INFILE"
+		else
+			cat "$INFILE" | egrep '^ATOM ' | cut -c 1-60 | sed 's/\s\+/ /g' | sed 's/\s\+$//'
+		fi
 	} \
 	| md5sum | awk '{print $1}' \
 	> "${TMPLDIR}/hashsum.txt"
 	
 	HASHSUM="voronota-js-only-global-voromqa-$(cat ${TMPLDIR}/hashsum.txt)"
 	
-	if [ -s "${CACHE_DIR}/${HASHSUM}.txt" ]
+	if [ -s "${CACHE_DIR}/${HASHSUM}.tar.gz" ]
 	then
-		cat "${CACHE_DIR}/${HASHSUM}.txt" \
-		| sed '1 s|^|input_name |' \
-		| sed "2 s|^|${INFILE_BASENAME} |" \
-		> "$TMPLDIR/output_table_file"
+		mkdir -p "${TMPLDIR}/saved_results"
 		
-		if [ "$OUTPUT_TABLE_FILE" == "_stdout" ]
+		cp "${CACHE_DIR}/${HASHSUM}.tar.gz" "${TMPLDIR}/saved_results/archive.tar.gz"
+		
+		cd "${TMPLDIR}/saved_results"
+		tar -xf "./archive.tar.gz"
+		cd - &> /dev/null
+		
+		if [ ! -s "${TMPLDIR}/saved_results/results_summary_table.txt" ]
 		then
-			cat "$TMPLDIR/output_table_file"
-		else
-			mkdir -p "$(dirname $OUTPUT_TABLE_FILE)"
-			mv "$TMPLDIR/output_table_file" "$OUTPUT_TABLE_FILE"
+			echo >&2 "Error: invalid cached archive '${CACHE_DIR}/${HASHSUM}.tar.gz'"
+			exit 1
 		fi
+		
+		"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR/saved_results"
 		
 		exit 0
 	fi
@@ -272,8 +446,8 @@ common_params.input_as_assembly='$AS_ASSEMBLY';
 common_params.restrict_input_atoms='$RESTRICT_INPUT';
 common_params.run_faspr='$RUN_FASPR';
 common_params.output_table_file='$TMPLDIR/output_table_file';
-var input_info_array=[];
-input_info_array.push({"input_file": "$INFILE", "input_file_name": "$INFILE_BASENAME"});
+common_params.output_adjuncts_file='$TMPLDIR/output_adjuncts_file';
+var input_info={"input_file": "$INFILE", "input_file_name": "$INFILE_BASENAME"}
 EOF
 
 cat << 'EOF'
@@ -310,8 +484,6 @@ if(params.output_table_file===undefined || params.output_table_file==="")
 	params.output_table_file="_stdout";
 }
 
-voronota_reset_time();
-
 voronota_delete_objects();
 
 if(params.input_is_script=="true")
@@ -337,8 +509,6 @@ if(params.run_faspr!="")
 	voronota_assert_full_success("Failed to run FASPR");
 }
 
-voronota_reset_time();
-
 voronota_construct_contacts();
 voronota_assert_full_success("Failed to construct inter-chain contacts");
 
@@ -349,6 +519,14 @@ var voromqa_light_result=voronota_last_output().results[0].output;
 voronota_voromqa_dark_global();
 voronota_assert_full_success("Failed to compute VoroMQA-dark scores");
 var voromqa_dark_result=voronota_last_output().results[0].output;
+
+voronota_set_adjunct_of_atoms_by_residue_pooling("-source-name", "voromqa_score_r", "-destination-name", "voromqa_score_rs0", "-pooling-mode min", "-smoothing-window", 0);
+voronota_assert_full_success("Failed to pool and smooth residue adjuncts");
+
+voronota_set_adjunct_of_atoms_by_residue_pooling("-source-name", "vd1", "-destination-name", "vd1_rs0", "-pooling-mode", "min", "-smoothing-window", 0);
+voronota_assert_full_success("Failed to pool and smooth residue dark adjuncts");
+
+voronota_export_adjuncts_of_atoms("-file", params.output_adjuncts_file, "-use", "[-aname CA]", "-adjuncts", ["vd1_rs0", "voromqa_score_rs0"], "-no-serial", "-no-name");
 
 var summary={}
 
@@ -390,22 +568,18 @@ voronota_setup_defaults("-no-load-alt-voromqa-potential -faster-load-voromqa-pot
 
 var full_summary_table="";
 
-for(var i=0;i<input_info_array.length;i++)
+try
 {
-	var subinput=input_info_array[i];
-	try
+	var summary_table=analyze_structure(common_params, input_info);
+	if(full_summary_table=="")
 	{
-		var summary_table=analyze_structure(common_params, subinput);
-		if(full_summary_table=="")
-		{
-			full_summary_table+=summary_table.header+"\n";
-		}
-		full_summary_table+=summary_table.row+"\n";
+		full_summary_table+=summary_table.header+"\n";
 	}
-	catch(error)
-	{
-		log("Failed with '"+subinput.input_file_name+"': "+error);
-	}
+	full_summary_table+=summary_table.row+"\n";
+}
+catch(error)
+{
+	log("Failed with '"+input_info.input_file_name+"': "+error);
 }
 
 fwrite('_virtual/summary', full_summary_table);
@@ -423,19 +597,24 @@ then
 	exit 1
 fi
 
+cat "$TMPLDIR/output_table_file" \
+| sed 's/^\S\+\s\+//' \
+> "$TMPLDIR/results_summary_table.txt"
+
+cat "$TMPLDIR/output_adjuncts_file" \
+> "$TMPLDIR/results_residue_scores.txt"
+
 if [ -n "$CACHE_DIR" ] && [ -n "$HASHSUM" ]
 then
+	cd "$TMPLDIR"
+	tar -czf "${HASHSUM}.tar.gz" "./results_summary_table.txt" "./results_residue_scores.txt"
+	cd - &> /dev/null
+
 	mkdir -p "$CACHE_DIR"
-	cat "$TMPLDIR/output_table_file" \
-	| sed 's/^\S\+\s\+//' \
-	> "$CACHE_DIR/${HASHSUM}.txt"
+	mv "${TMPLDIR}/${HASHSUM}.tar.gz" "$CACHE_DIR/${HASHSUM}.tar.gz"
 fi
 
-if [ "$OUTPUT_TABLE_FILE" == "_stdout" ]
-then
-	cat "$TMPLDIR/output_table_file"
-else
-	mkdir -p "$(dirname $OUTPUT_TABLE_FILE)"
-	mv "$TMPLDIR/output_table_file" "$OUTPUT_TABLE_FILE"
-fi
+"$ZEROARG" "${ALLARGS[@]}" --jofd "$TMPLDIR"
+
+exit 0
 
